src/Entity/CashFlow.php
<?php

namespace App\Entity;

use App\Repository\CashFlowRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CashFlowRepository::class)]
class CashFlow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_cash_flow = null;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2)]
    private $value;
    #[ORM\Column(type: "text", nullable: true)]
    private $description;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $type;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $type_transactiion;

    #[ORM\Column(type: "string", length: 255, nullable: true)]
    private $bank;

    #[ORM\Column(type: "string", length: 255,nullable: true)]
    private $currency;

    #[ORM\Column(type: "string", length: 255,nullable: true)]
    private $currency_to;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2,nullable: true)]
    private $current_convert;

    #[ORM\Column(type: "string", length: 255,nullable: true)]
    private $merchant;

    #[ORM\Column(type: "datetime")]
    private $date;

    #[ORM\Column(type: "datetime")]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: TypeFlow::class)]
    #[ORM\JoinColumn(name: "id_type_flow", referencedColumnName: "id_type_flow"),]
    private ?TypeFlow $typeFlow;

    /**
     * @return TypeFlow|null
     */
    public function getTypeFlow(): ?TypeFlow
    {
        return $this->typeFlow;
    }

    /**
     * @param TypeFlow|null $typeFlow
     */
    public function setTypeFlow(?TypeFlow $typeFlow): void
    {
        $this->typeFlow = $typeFlow;
    }

    /**
     * @return mixed
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @param mixed $value
     */
    public function setValue($value): void
    {
        $this->value = $value;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date): void
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     */
    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    public function getIdCashFlow(): ?int
    {
        return $this->id_cash_flow;
    }

    /**
     * @return mixed
     */
    public function getTypeTransactiion()
    {
        return $this->type_transactiion;
    }

    /**
     * @param mixed $type_transactiion
     */
    public function setTypeTransactiion($type_transactiion): void
    {
        $this->type_transactiion = $type_transactiion;
    }

    /**
     * @return mixed
     */
    public function getBank()
    {
        return $this->bank;
    }

    /**
     * @param mixed $bank
     */
    public function setBank($bank): void
    {
        $this->bank = $bank;
    }

    /**
     * @return mixed
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * @param mixed $currency
     */
    public function setCurrency($currency): void
    {
        $this->currency = $currency;
    }

    /**
     * @return mixed
     */
    public function getCurrencyTo()
    {
        return $this->currency_to;
    }

    /**
     * @param mixed $currency_to
     */
    public function setCurrencyTo($currency_to): void
    {
        $this->currency_to = $currency_to;
    }

    /**
     * @return mixed
     */
    public function getCurrentConvert()
    {
        return $this->current_convert;
    }

    /**
     * @param mixed $current_convert
     */
    public function setCurrentConvert($current_convert): void
    {
        $this->current_convert = $current_convert;
    }

    /**
     * @return mixed
     */
    public function getMerchant()
    {
        return $this->merchant;
    }

    /**
     * @param mixed $merchant
     */
    public function setMerchant($merchant): void
    {
        $this->merchant = $merchant;
    }



}

src/Entity/TypeFlow.php
<?php

namespace App\Entity;

use App\Repository\TypeFlowRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TypeFlowRepository::class)]
class TypeFlow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_type_flow = null;
    #[ORM\Column]
    private ?string $title;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "id_user", referencedColumnName: "id_user")]
    private ?User $user;

    public function getIdTypeFlow(): ?int
    {
        return $this->id_type_flow;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string|null $title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User|null $user
     */
    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

}

src/Controller/CashFlowController.php
<?php

namespace App\Controller;

use App\Entity\CashFlow;
use App\Entity\TypeFlow;
use App\Helper\ConvertDatesTime;
use App\Repository\CashFlowRepository;
use App\Repository\TypeFlowRepository;
use App\Repository\UserRepository;
use App\Service\ExcelService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class CashFlowController extends Controller
{
    #[Route('/cashFlow/create', name: 'app_cash_flow_create', methods:["POST","GET"])]
    public function index(Request $request, EntityManagerInterface $entityManager, SessionInterface $session): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',['path' => $this->getPathEnv()]);
        }

        if ($request->isMethod('POST')) {

            $description = $request->request->get('description');
            $value = $request->request->get('value');
            $type = $request->request->get('type');
            $date = $request->request->get('date');
            $category = $request->request->get("category");
            $bank = $request->request->get("bank");
            $currency = $request->request->get("currency");

            $cashFlow = new CashFlow();
            $cashFlow->setValue($value);
            $cashFlow->setType($type);
            $cashFlow->setDate(new \DateTime($date));
            $cashFlow->setCreatedAt(new \DateTime());
            $cashFlow->setDescription($description);
            $cashFlow->setBank($bank);
            $cashFlow->setCurrency($currency);

            if(!empty($category)) {
                $categoryEntity = $entityManager->getRepository(TypeFlow::class)->find($category);
                $cashFlow->setTypeFlow($categoryEntity);
            }

            $entityManager->persist($cashFlow);
            $entityManager->flush();

            return $this->redirectToRoute('app_cash_flow_all');
        }

        return $this->render('cash_flow/create-view.html.twig',['session'=> $this->sessionDTO,'path' => $this->getPathEnv()]);

    }

    #[Route('/cashFlow/update/{id}', name: 'app_cash_flow_update', methods:["POST","GET"])]
    public function update(Request $request, EntityManagerInterface $entityManager,int $id,
                           CashFlowRepository $cashFlowRepository,
                           TypeFlowRepository $typeFlowRepository,
                    SessionInterface $session): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',['path' => $this->getPathEnv()]);
        }

        if ($request->isMethod('POST')) {

            $description = $request->request->get('description');
            $value = $request->request->get('value');
            $type = $request->request->get('type');
            $date = $request->request->get('date');
            $category = $request->request->get("category");


            $cashFlow = $cashFlowRepository->find($id);

            if (!$cashFlow) {
                throw $this->createNotFoundException('not found');
            }

            if(!empty($category)) {
                $typeFlow = $typeFlowRepository->find($category);

                if(!$typeFlow) {
                    throw $this->createNotFoundException('type error');
                }

                $cashFlow->setTypeFlow($typeFlow);
            }

            $cashFlow->setValue($value);
            $cashFlow->setType($type);
            $cashFlow->setDate(new \DateTime($date));
            $cashFlow->setCreatedAt(new \DateTime());
            $cashFlow->setDescription($description);

            $entityManager->persist($cashFlow);
            $entityManager->flush();

            return $this->redirectToRoute('app_cash_flow_all');
        }

        return $this->redirectToRoute('edit_cash_flow', ['id' => $id]);

    }

    #[Route('/cashFlow/view/create', name: 'create_cash_flow', methods:["GET"])]
    public function createView(SessionInterface $session,
                               TypeFlowRepository $typeFlowRepository,
                               UserRepository $userRepository): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig');
        }

        $user = $userRepository->find($this->sessionDTO->getIdUser());
        $categories = $typeFlowRepository->findBy(['user' => $user]);

        return $this->render('cash_flow/create-view.html.twig',
            [
                'session'=> $this->sessionDTO,
                'categories'=> $categories,
                'path' => $this->getPathEnv()]);
    }

    //app_cash_flow_uplaod_bank
    #[Route('/cashFlow/view/upload-bank', name: 'app_cash_flow_uplaod_bank', methods:["GET"])]
    public function uploadBankView(SessionInterface $session): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig');
        }

        return $this->render('cash_flow/upload-view.html.twig',
            ['session'=> $this->sessionDTO,
                'path' => $this->getPathEnv()]);
    }

    //app_cash_flow_filter

    #[Route('/cashFlow/all/filter', name: 'app_cash_flow_filter', methods:["POST", "GET"])]
    public function getAllFilter(Request $request, CashFlowRepository $cashFlowRepository,
                                 SessionInterface $session, UserRepository $userRepository, TypeFlowRepository $typeFlowRepository): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',['path' => $this->getPathEnv()]);
        }

        if ($request->isMethod('POST')) {

            $bank = $request->request->get("bank");
            $search = $request->request->get("search");
            $start = $request->request->get("start");
            $end = $request->request->get("end") ?? date("Y-m-d");
            $status = $request->request->get("status");
            $currency = $request->request->get("currency")??"EUR";
            $category = $request->request->get("category");


            $list = $cashFlowRepository->filter($bank, $search, $start, $end, $status, $currency,$category);

            $currencyTo = "BRL";

            $total = $cashFlowRepository->getTotalAmountForBankAndCurrencyFilter($bank, $currencyTo, $search, $start, $end, $status, $currency,$category);

            if($currency == "EUR") {
                $route = 'cash_flow/index.html.twig';
            }elseif($currency == "BRL"){
                $route = 'cash_flow/brazil/index.html.twig';
            }

            $user = $userRepository->find($this->sessionDTO->getIdUser());
            $categories = $typeFlowRepository->findBy(['user' => $user]);
            return $this->render($route, [
                'cashFlows' => $list,
                'total_real' => $total[0]["total"] ?? 0,
                "bank"=> $bank,
                "search"=>$search,
                "start"=> $start,
                "end"=>$end,
                "status"=>$status,
                'session'=> $this->sessionDTO,
                'category'=>$category,
                'categories'=> $categories,
                'path' => $this->getPathEnv(),
            ]);

        }

        return $this->redirectToRoute('app_dashboard');

    }

    #[Route('/cashFlow/all/brazil', name: 'app_cash_flow_all_brazil', methods:["GET"])]
    public function getAllBrazil(Request $request, CashFlowRepository $cashFlowRepository, SessionInterface $session): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig');
        }

        $currency = "BRL";

        $list = $cashFlowRepository->findBy(['currency' => $currency], ['date' => 'DESC', 'id_cash_flow' => 'DESC']);

        $bank = "Wise";
        $currencyTo = "BRL";

        $total = $cashFlowRepository->getTotalAmountForBankAndCurrency($bank, $currencyTo, $currency);

        return $this->render('cash_flow/brazil/index.html.twig', [
            'cashFlows' => $list,
            'total_real'=> $total,
            'session'=> $this->sessionDTO,
            'path' => $this->getPathEnv(),
        ]);
    }


    #[Route('/cashFlow/all', name: 'app_cash_flow_all', methods:["GET"])]
    public function getAll(Request $request, CashFlowRepository $cashFlowRepository,
                           SessionInterface $session,
                           TypeFlowRepository $typeFlowRepository, UserRepository $userRepository): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',[ 'path' => $this->getPathEnv()]);
        }

        $currency = "EUR";

        $list = $cashFlowRepository->findBy(['currency' => $currency], ['date' => 'DESC', 'id_cash_flow' => 'DESC']);

        $bank = "Wise";
        $currencyTo = "BRL";

        $user = $userRepository->find($this->sessionDTO->getIdUser());
        $categories = $typeFlowRepository->findBy(['user' => $user]);

        $total = $cashFlowRepository->getTotalAmountForBankAndCurrency($bank, $currencyTo, $currency);

        return $this->render('cash_flow/index.html.twig', [
            'cashFlows' => $list,
            'total_real'=> $total,
            'session'=> $this->sessionDTO,
            'categories'=> $categories,
            'path' => $this->getPathEnv(),
        ]);
    }

    #[Route('/cashFlow/edit/{id}', name: 'edit_cash_flow', methods:["GET"])]
    public function editCashFlow(Request $request, CashFlowRepository $cashFlowRepository,
                                 int $id, SessionInterface $session,

templates/cash_flow/create-view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cash Flow{% endblock %}

{% block body %}
<div class="main-panel">
    <div class="content-wrapper">

                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Register money inflow or outflow</h4>
                            <form class="form-sample" action="{{ path('app_cash_flow_create') }}" method="POST">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Description</label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="description" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Value</label>
                                            <div class="col-sm-4">
                                                <input type="number" class="form-control" name="value" />
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Type</label>
                                            <div class="col-sm-9">
                                                <select class="form-control" name="type">
                                                    <option>Deposit</option>
                                                    <option selected>Out</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Date</label>
                                            <div class="col-sm-9">
                                                <input id="dateInput" type="date" class="form-control" placeholder="dd/mm/yyyy" name="date" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Category</label>
                                            <div class="col-sm-9">
                                                <select class="form-control" name="category">
                                                    <option></option>
                                                    {% for category in categories %}
                                                        <option value="{{ category.idTypeFlow }}">{{ category.title }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <input type="hidden" name="currency" value="EUR">

                                    <label class="col-sm-1 col-form-label">Bank</label>
                                    <div class="col-sm-2">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" name="bank" value="Wise"

                                                > Wise </label>
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" name="bank" value="Revolut"

                                                > Revolut </label>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
</div>
</div>

    <script>
        // Obtém a data atual
        const currentDate = new Date();

        // Formata a data como dd/mm/yyyy
        const day = String(currentDate.getDate()).padStart(2, '0');
        const month = String(currentDate.getMonth() + 1).padStart(2, '0'); // Mês começa em zero
        const year = currentDate.getFullYear();

        // Define a data no campo de entrada
        const dateInput = document.getElementById('dateInput');
        dateInput.value = `${day}/${month}/${year}`;


    </script>


{% endblock %}

templates/cash_flow/edit-view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cash Flow{% endblock %}

{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">

            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Edit money inflow or outflow</h4>
                        <form class="form-sample" action="{{ path('app_cash_flow_update', {'id': cashFlow.idCashFlow}) }}" method="POST">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Description</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="description" value="{{ cashFlow.description }}" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Value £</label>
                                        <div class="col-sm-4">
                                            <input type="number" class="form-control" name="value" value="{{ cashFlow.value }}" />
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Type</label>
                                        <div class="col-sm-9">
                                            <select class="form-control" name="type">
                                                <option {{ cashFlow.type=='Deposit'?"selected":""}}>Deposit</option>
                                                <option {{ cashFlow.type=='Out'?"selected":""}}>Out</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Date</label>
                                        <div class="col-sm-9">
                                            <input class="form-control" name="date" type="date" value="{{ cashFlow.date|date('Y-m-d') }}" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Category</label>
                                        <div class="col-sm-9">
                                            <select class="form-control" name="category">
                                                <option></option>
                                                {% for category in categories %}
                                                    <option value="{{ category.idTypeFlow }}"
                                                            {% if cashFlow is not null and cashFlow.typeFlow is not null %}
                                                                {% if category.idTypeFlow == cashFlow.typeFlow.idTypeFlow %}
                                                                    selected
                                                                {% endif %}
                                                            {% endif %}
                                                    >{{ category.title }}</option>
                                                {% endfor %}

                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <input type="hidden" name="currency" value="EUR">

                                <label class="col-sm-1 col-form-label">Bank</label>
                                <div class="col-sm-2">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="bank" value="Wise"
                                                    {% if cashFlow.bank == "Wise" %}
                                                        checked
                                                    {% endif  %}

                                            > Wise </label>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="bank" value="Revolut"
                                                    {% if cashFlow.bank == "Revolut" %}
                                                        checked
                                                    {% endif  %}

                                            > Revolut </label>
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const dateInput = document.getElementById('dateInput');
        dateInput.value = `${day}/${month}/${year}`;
    </script>


{% endblock %}

templates/cash_flow/upload-view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cash Flow{% endblock %}

{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">

            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">upload bank statement</h4>
                        <form class="form-sample" action="{{ path('upload_cash_flow_csv') }}" method="POST" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>File upload</label>
                                        <input type="file" name="img[]" class="file-upload-default">
                                        <div class="input-group col-xs-12">
                                            <input type="file" class="form-control file-upload-info" name="upload">
                                            <span class="input-group-append">
                                                <button class="file-upload-browse btn btn-gradient-primary" type="submit">Upload</button>
                                              </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-3 col-form-label">Bank</label>
                                        <div class="col-sm-9">
                                            <select class="form-control" name="bank">
                                                <option selected>Revolut</option>
                                                <option >Wise</option>
                                                <option >Nubank</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Obtém a data atual
        const currentDate = new Date();

        // Formata a data como dd/mm/yyyy
        const day = String(currentDate.getDate()).padStart(2, '0');
        const month = String(currentDate.getMonth() + 1).padStart(2, '0'); // Mês começa em zero
        const year = currentDate.getFullYear();

        // Define a data no campo de entrada
        const dateInput = document.getElementById('dateInput');
        dateInput.value = `${day}/${month}/${year}`;


    </script>


{% endblock %}