src/Entity/Bitcoin.php
<?php

namespace App\Entity;

use App\Repository\BitcoinRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BitcoinRepository::class)]
class Bitcoin
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_bitcoin = null;

    #[ORM\Column]
    private ?string $symbol = null;

    #[ORM\Column]
    private ?string $description = null;

    #[ORM\Column]
    private ?string $currency = null;

    #[ORM\Column]
    private ?string $base_currency = null;

    #[ORM\Column(nullable: true)]
    private ?string $ticker = null;

    /**
     * @return string|null
     */
    public function getTicker(): ?string
    {
        return $this->ticker;
    }

    /**
     * @param string|null $ticker
     */
    public function setTicker(?string $ticker): void
    {
        $this->ticker = $ticker;
    }

    public function build(array $dados): void
    {
        $this->symbol = $dados['symbol'] ?? null;
        $this->description = $dados['description'] ?? null;
        $this->currency = $dados['currency'] ?? null;
        $this->base_currency = $dados['base-currency'] ?? null;
    }

    /**
     * @return string|null
     */
    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    /**
     * @param string|null $symbol
     */
    public function setSymbol(?string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return string|null
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * @param string|null $currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * @return string|null
     */
    public function getBaseCurrency(): ?string
    {
        return $this->base_currency;
    }

    /**
     * @param string|null $base_currency
     */
    public function setBaseCurrency(?string $base_currency): void
    {
        $this->base_currency = $base_currency;
    }

    public function getIdBitcoin(): ?int
    {
        return $this->id_bitcoin;
    }


}

src/Entity/Ticker.php
<?php

namespace App\Entity;

use App\Repository\TickerRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TickerRepository::class)]
class Ticker
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_ticker = null;
    #[ORM\Column]
    private ?string $buy = null;
    #[ORM\Column]
    private ?string $high = null;
    #[ORM\Column]
    private ?string $last = null;
    #[ORM\Column]
    private ?string $low = null;
    #[ORM\Column]
    private ?string $open = null;

    #[ORM\Column]
    private ?string $pair = null;

    #[ORM\Column]
    private ?string $sell = null;

    #[ORM\Column]
    private ?string $vol = null;

    #[ORM\Column]
    private ?int $date = null;

    #[ORM\Column(type: "datetime")]
    private \DateTime $date_real;


    #[ORM\ManyToOne(targetEntity: Bitcoin::class)]
    #[ORM\JoinColumn(name: "id_bitcoin", referencedColumnName: "id_bitcoin"),]
    private ?Bitcoin $bitcoin;

    /**
     * @return Bitcoin|null
     */
    public function getBitcoin(): ?Bitcoin
    {
        return $this->bitcoin;
    }

    /**
     * @param Bitcoin|null $bitcoin
     */
    public function setBitcoin(?Bitcoin $bitcoin): void
    {
        $this->bitcoin = $bitcoin;
    }

    public function getIdTicker(): ?int
    {
        return $this->id_ticker;
    }

    /**
     * @return string|null
     */
    public function getBuy(): ?string
    {
        return $this->buy;
    }

    /**
     * @param string|null $buy
     */
    public function setBuy(?string $buy): void
    {
        $this->buy = $buy;
    }

    /**
     * @return string|null
     */
    public function getHigh(): ?string
    {
        return $this->high;
    }

    /**
     * @param string|null $high
     */
    public function setHigh(?string $high): void
    {
        $this->high = $high;
    }

    /**
     * @return string|null
     */
    public function getLast(): ?string
    {
        return $this->last;
    }

    /**
     * @param string|null $last
     */
    public function setLast(?string $last): void
    {
        $this->last = $last;
    }

    /**
     * @return string|null
     */
    public function getLow(): ?string
    {
        return $this->low;
    }

    /**
     * @param string|null $low
     */
    public function setLow(?string $low): void
    {
        $this->low = $low;
    }

    /**
     * @return string|null
     */
    public function getOpen(): ?string
    {
        return $this->open;
    }

    /**
     * @param string|null $open
     */
    public function setOpen(?string $open): void
    {
        $this->open = $open;
    }

    /**
     * @return string|null
     */
    public function getPair(): ?string
    {
        return $this->pair;
    }

    /**
     * @param string|null $pair
     */
    public function setPair(?string $pair): void
    {
        $this->pair = $pair;
    }

    /**
     * @return string|null
     */
    public function getSell(): ?string
    {
        return $this->sell;
    }

    /**
     * @param string|null $sell
     */
    public function setSell(?string $sell): void
    {
        $this->sell = $sell;
    }

    /**
     * @return string|null
     */
    public function getVol(): ?string
    {
        return $this->vol;
    }

    /**
     * @param string|null $vol
     */
    public function setVol(?string $vol): void
    {
        $this->vol = $vol;
    }

    /**
     * @return int|null
     */
    public function getDate(): ?int
    {
        return $this->date;
    }

    /**
     * @param int|null $date
     */
    public function setDate(?int $date): void
    {
        $this->date = $date;
    }

    /**
     * @return \DateTime
     */
    public function getDateReal(): \DateTime
    {
        return $this->date_real;
    }

    /**
     * @param \DateTime $date_real
     */
    public function setDateReal(\DateTime $date_real): void
    {
        $this->date_real = $date_real;
    }

  /*  [
    {
    "buy": "160.00000005",
    "date": 1636107279,
    "high": "145.00000001",
    "last": "144.07000004",
    "low": "143.00000002",
    "open": "143.00000007",
    "pair": "BTC-BRL",
    "sell": "145.00000006",
    "vol": "84.00100003"
    }
    ]*/

}

src/Controller/BitcoinController.php
<?php

namespace App\Controller;

use App\Entity\Bitcoin;
use App\Entity\Ticker;
use App\Repository\BitcoinRepository;
use App\Repository\TickerRepository;
use DateTime;
use Doctrine\DBAL\Driver\Exception;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class BitcoinController extends Controller
{
    #[Route('/bitcoinList', name: 'app_bitcoin')]
    public function index(SessionInterface $session, BitcoinRepository $bitcoinRepository): Response
    {

        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',[ 'path' => $this->getPathEnv(),]);
        }

        return $this->render('bitcoin/index.html.twig', [
            'path' => $this->getPathEnv(),
            'object'=> "Coin",
            'list'=> $bitcoinRepository->findAll(),
            'session'=> $this->sessionDTO,
            'title'=> 'List of Coins',
        ]);
    }

    #[Route('/tickerList/{id_bitcoin}', name: 'app_bitcoin_list_ticker')]
    public function listTicker(SessionInterface $session, int $id_bitcoin, BitcoinRepository $bitcoinRepository, TickerRepository $tickerRepository): Response
    {

        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',[ 'path' => $this->getPathEnv(),]);
        }

        $bitcoin  = $bitcoinRepository->find($id_bitcoin);

        return $this->render('bitcoin/ticker.html.twig', [
            'path' => $this->getPathEnv(),
            'object'=> "Ticker",
            'list'=> $tickerRepository->findBy(["bitcoin"=> $bitcoin],["date_real"=> 'DESC']),
            'session'=> $this->sessionDTO,
            'title'=> 'List of Ticker',
        ]);
    }


    #[Route('/symbols', name: 'app_bitcoin_symbol')]
    public function symbols(EntityManagerInterface $entityManager): Response
    {

        die("stop");

        $datas = file_get_contents("https://api.mercadobitcoin.net/api/v4/symbols");

        $dados = json_decode($datas,true);


        $dadosPersistencia = [];

        // Iteramos pelos índices
        for ($i = 0; $i < count($dados["symbol"]); $i++) {
            // Iteramos pelas chaves
            foreach (array_keys($dados) as $chave) {
                // Criamos o array persistido se ainda não existir
                if (!isset($dadosPersistencia[$i])) {
                    $dadosPersistencia[$i] = [];
                }

                // Adicionamos o valor ao array persistido
                $dadosPersistencia[$i][$chave] = $dados[$chave][$i];
            }
        }


        foreach ($dadosPersistencia as $item) {

            $bitcoin = new Bitcoin();
            $bitcoin->build($item);

            $entityManager->persist($bitcoin);

        }

        $entityManager->flush();
    }

    #[Route('/ticker', name: 'app_bitcoin_ticker')]
    public function ticker(BitcoinRepository $bitcoinRepository, EntityManagerInterface $entityManager)
    {

        try {

            $list = $bitcoinRepository->findBy(["ticker" => '1']);

            foreach ($list as $item) {

                $response = file_get_contents("https://api.mercadobitcoin.net/api/v4/tickers?symbols=" . $item->getSymbol());

                $data = json_decode($response, true);

                if (!isset($data[0]["buy"])) {
                    continue;
                }

                $data = $data[0];

                $ticker = new Ticker();
                $ticker->setBitcoin($item);
                $ticker->setBuy($data["buy"]);
                $ticker->setHigh($data["high"]);
                $ticker->setLast($data["last"]);
                $ticker->setLow($data["low"]);
                $ticker->setOpen($data["open"]);
                $ticker->setPair($data["pair"]);
                $ticker->setSell($data["sell"]);
                $ticker->setVol($data["vol"]);
                $ticker->setDate($data["date"]);

                $dateTime = new DateTime();
                $dateTime->setTimestamp($data["date"]);

                $ticker->setDateReal($dateTime);

                $entityManager->persist($ticker);
                $entityManager->flush();
            }



            return $this->redirectToRoute('app_bitcoin');
        }catch (Exception $e) {
            dd($e->getMessage());
        }
    }
}

templates/bitcoin/index.html.twig
{% extends 'base.html.twig' %}

{% block css %}

    <link rel="stylesheet" href="{{ asset(path ~'vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'vendors/css/vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'css/demo_1/style.css')}}">
    <link rel="shortcut icon" href="{{ asset(path ~'images/favicon.ico')}}" />

{% endblock %}

{% block title %} Bitcoin{% endblock %}

{% block body %}
<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <form  action="" method="POST" >
                <button type="submit" class="btn btn-gradient-dark btn-fw">+ Adicionar</button>
            </form>
            <h3 class="page-title"> {{title}} </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">{{title}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ object }}</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{title}}</h4>
                <div class="row">
                    <div class="col-12">
                        <table id="order-listing" class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Symbol</th>
                                <th>Description</th>
                                <th>Currency</th>
                                <th>Base Currency</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for item in list %}

                                <tr>
                                    <td>{{ item.IdBitcoin }}</td>
                                    <td>{{ item.symbol }}  </td>
                                    <td>{{ item.description }}</td>
                                    <td>{{ item.currency }}</td>
                                    <td>{{ item.baseCurrency }}</td>
                                    <td>
                                        <form action="{{ path('app_bitcoin_list_ticker', {'id_bitcoin': item.idBitcoin}) }}"><button type="submit" class="btn btn-outline-primary">Ticker</button></form>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
        </div>
    </footer>

    <script src=".{{ asset(path ~'vendors/js/vendor.bundle.base.js')}}"></script>
    <script src="{{ asset(path ~'vendors/datatables.net/jquery.dataTables.js')}}"></script>
    <script src="{{ asset(path ~'vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
    <script src="{{ asset(path ~'js/off-canvas.js')}}"></script>
    <script src="{{ asset(path ~'js/hoverable-collapse.js')}}"></script>
    <script src="{{ asset(path ~'js/misc.js')}}"></script>
    <script src="{{ asset(path ~'js/settings.js')}}]"></script>
    <script src="{{ asset(path ~'js/todolist.js')}}"></script>
    <script src="{{ asset(path ~'js/jquery.cookie.js')}}"></script>
    <script src="{{ asset(path ~'js/data-table.js')}}"></script>

    {% endblock %}

templates/bitcoin/ticker.html.twig
{% extends 'base.html.twig' %}

{% block css %}

    <link rel="stylesheet" href="{{ asset(path ~'vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'vendors/css/vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'css/demo_1/style.css')}}">
    <link rel="shortcut icon" href="{{ asset(path ~'images/favicon.ico')}}" />

{% endblock %}

{% block title %} Bitcoin{% endblock %}

{% block body %}
<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{title}}</h4>
                <div class="row">
                    <div class="col-12">
                        <table id="order-listing" class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Coin</th>
                                <th>buy</th>
                                <th>high</th>
                                <th>last</th>
                                <th>low</th>
                                <th>open</th>
                                <th>pair</th>
                                <th>sell</th>
                                <th>vol</th>
                                <th>date</th>

                            </tr>
                            </thead>
                            <tbody>

                            {% for item in list %}

                                <tr>
                                    <td>{{ item.Idticker }}</td>
                                    <td>{{ item.getBitcoin().description }}  </td>
                                    <td>{{ item.buy }}</td>
                                    <td>{{ item.high }}</td>
                                    <td>{{ item.last }}</td>
                                    <td>{{ item.low }}</td>
                                    <td>{{ item.open }}</td>
                                    <td>{{ item.pair }}</td>
                                    <td>{{ item.sell }}</td>
                                    <td>{{ item.vol }}</td>
                                    <td>{{ item.dateReal | date('d-m-Y') }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
        </div>
    </footer>

    <script src=".{{ asset(path ~'vendors/js/vendor.bundle.base.js')}}"></script>
    <script src="{{ asset(path ~'vendors/datatables.net/jquery.dataTables.js')}}"></script>
    <script src="{{ asset(path ~'vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
    <script src="{{ asset(path ~'js/off-canvas.js')}}"></script>
    <script src="{{ asset(path ~'js/hoverable-collapse.js')}}"></script>
    <script src="{{ asset(path ~'js/misc.js')}}"></script>
    <script src="{{ asset(path ~'js/settings.js')}}]"></script>
    <script src="{{ asset(path ~'js/todolist.js')}}"></script>
    <script src="{{ asset(path ~'js/jquery.cookie.js')}}"></script>
    <script src="{{ asset(path ~'js/data-table.js')}}"></script>

    {% endblock %}