src/Entity/Debts.php
<?php

namespace App\Entity;

use App\Repository\DebtsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DebtsRepository::class)]
class Debts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_debts = null;
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: "id_user", referencedColumnName: "id_user")]
    private ?User $user;
    #[ORM\ManyToOne(targetEntity: TypeFlow::class)]
    #[ORM\JoinColumn(name: "id_type_flow", referencedColumnName: "id_type_flow"),]
    private ?TypeFlow $typeFlow;
    #[ORM\Column(nullable: true)]
    private ?string $describe;

    #[ORM\Column(nullable: true)]
    private ?string $ui_generate;

    #[ORM\Column(nullable: true)]
    private ?string $service;
    #[ORM\Column(type: "decimal", precision: 10, scale: 2)]
    private $amount;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2,nullable: true)]
    private $total;
    #[ORM\Column(nullable: true)]
    private ?int $portion;

    #[ORM\Column (nullable: true)]
    private ?int $number_of_installments;

    #[ORM\Column(type: "date")]
    private $date;

    #[ORM\Column(type: "datetime")]
    private $createdAt;

    /**
     * @return TypeFlow|null
     */
    public function getTypeFlow(): ?TypeFlow
    {
        return $this->typeFlow;
    }

    /**
     * @param TypeFlow|null $typeFlow
     */
    public function setTypeFlow(?TypeFlow $typeFlow): void
    {
        $this->typeFlow = $typeFlow;
    }

    public function getIdDebts(): ?int
    {
        return $this->id_debts;
    }

    /**
     * @return string|null
     */
    public function getUiGenerate(): ?string
    {
        return $this->ui_generate;
    }

    /**
     * @param string|null $ui_generate
     */
    public function setUiGenerate(?string $ui_generate): void
    {
        $this->ui_generate = $ui_generate;
    }


    /**
     * @return mixed
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * @param mixed $total
     */
    public function setTotal($total): void
    {
        $this->total = $total;
    }


    /**
     * @return string|null
     */
    public function getDescribe(): ?string
    {
        return $this->describe;
    }

    /**
     * @param string|null $describe
     */
    public function setDescribe(?string $describe): void
    {
        $this->describe = $describe;
    }

    /**
     * @return mixed
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param mixed $amount
     */
    public function setAmount($amount): void
    {
        $this->amount = $amount;
    }

    /**
     * @return int|null
     */
    public function getPortion(): ?int
    {
        return $this->portion;
    }

    /**
     * @param int|null $portion
     */
    public function setPortion(?int $portion): void
    {
        $this->portion = $portion;
    }

    /**
     * @return int|null
     */
    public function getNumberOfInstallments(): ?int
    {
        return $this->number_of_installments;
    }

    /**
     * @param int|null $number_of_installments
     */
    public function setNumberOfInstallments(?int $number_of_installments): void
    {
        $this->number_of_installments = $number_of_installments;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date): void
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     */
    public function setCreatedAt($createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User|null $user
     */
    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    /**
     * @return string|null
     */
    public function getService(): ?string
    {
        return $this->service;
    }

    /**
     * @param string|null $service
     */
    public function setService(?string $service): void
    {
        $this->service = $service;
    }

}

src/Controller/DebtsController.php
<?php

namespace App\Controller;

use App\Entity\Debts;
use App\Entity\User;
use App\Repository\DebtsRepository;
use App\Repository\UserRepository;
use Cassandra\Date;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use setasign\Fpdi\Fpdi;
use Smalot\PdfParser\Parser;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class DebtsController extends Controller
{
    #[Route('/debts/register', name: 'app_debts_register_view')]
    public function index(): Response
    {
        return $this->render('debts/index.html.twig', [
            'controller_name' => 'DebtsController',
        ]);
    }

    #[Route('/debts/list/filter', name: 'app_debts_filter', methods:["POST", "GET"])]
    public function getAllFilter(Request $request,DebtsRepository $debtsRepository,
                                 SessionInterface $session): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',[ 'path' => $this->getPathEnv(),]);
        }

        if ($request->isMethod('POST')) {

            $service = $request->request->get("service");
            $search = $request->request->get("search");
            $start = $request->request->get("start");
            $end = $request->request->get("end") ?? date("Y-m-d");
            $type = $request->request->get("type");

            $list = $debtsRepository->filter($service, $search, $start, $end);

            return $this->render('debts/index.html.twig', [
                'debts' => $list,
                "bank"=> $service,
                "search"=>$search,
                "start"=> $start,
                "end"=>$end,
                "type"=>$type,
                "title"=> "List Investments",
                'session'=> $this->sessionDTO,
                'path' => $this->getPathEnv(),
            ]);

        }

        return $this->redirectToRoute('app_debts_list');

    }

    #[Route('/debts/list', name: 'app_debts_list')]
    public function list(SessionInterface $session, DebtsRepository $debtsRepository, UserRepository $userRepository): Response
    {
        if (($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig');
        }

        $user =  $userRepository->findOneBy(["id_user"=>$this->sessionDTO->getIdUser()]);

        $debts =  $debtsRepository->findBy(["user"=> $user]);


        return $this->render('debts/index.html.twig', [
            'controller_name' => 'DebtsController',
            'session'=> $this->sessionDTO,
            'debts'=> $debts,
            'title'=>'List of Debts',
            'path' => $this->getPathEnv(),
        ]);
    }

    #[Route('/debts/upload/view', name: 'app_debts_upload_view')]
    public function uploadView(SessionInterface $session): Response
    {
        if (($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig');
        }
        return $this->render('debts/upload-view.html.twig', [
            'controller_name' => 'DebtsController',
            'title'=>"Upload Debts",
            'session'=> $this->sessionDTO,
            'path' => $this->getPathEnv(),
        ]);
    }

    /**
     * @throws \Exception
     */
    #[Route('/debts/upload', name: 'upload_debts_create', methods:["POST"])]
    public function create(Request $request,
                           EntityManagerInterface $entityManager,
                           SessionInterface $session): Response
    {
        if (($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig');
        }

        if ($request->isMethod('POST')) {

            $uploadedFile = $request->files->get('upload');

            $parser = new Parser();


            $pdf = $parser->parseFile($uploadedFile->getRealPath());

            $pageCount = count($pdf->getPages());

            $lastPage = $pdf->getPages()[$pageCount - 1];

            $text = $lastPage->getText();

            $pdfLines = explode(PHP_EOL, $text);

            $lines  =[];
            foreach ($pdfLines as $line) {

                $lines[]=  $line;
            }

            $transactions = [];
            $currentTransaction = [];

            foreach ($lines as $line) {

                $line = trim($line);

                if (!empty($line)) {

                    $currentTransaction[] = $line;
                } elseif (!empty($currentTransaction)) {
                    $transactions[] = implode(' ', $currentTransaction);
                    $currentTransaction = [];
                }
            }

            if (!empty($currentTransaction)) {
                $transactions[] = implode(' ', $currentTransaction);
            }

            $arrayTransacao = [];
            $i=0;
            $array = false;
            $sum = 0;
            foreach ($transactions as $transaction) {

                if($this->validarData($transaction)) {

                    $array = true;
                }

                if($array) {

                    if( (strpos($transaction, 'USD') !== false) && $i >0) {
                        continue;
                    }

                    if( (strpos($transaction, 'Pagamento em ') !== false) && $i >0) {

                        $foundPay  =$transaction;
                    }

                    $new[$i++] = $transaction;


                    if($i > 2) {

                        if(isset($foundPay) && $foundPay != $transaction) {
                            $new[2] = "-".$new[2];
                            unset($foundPay);
                        }else{
                            $format = str_replace(",",".",$new[2]);
                            $sum = $sum + $format;
                        }

                        $arrayTransacao[] = $new;
                        $i=0;
                        $array = false;

                    }

                    if((strpos($transaction, "/")) !==false) {
                        $new[3] = $this->getText($transaction);
                    }

                }

            }

            if(sizeof($arrayTransacao)==0) {
                return $this->render('debts/upload.html.twig', [
                    'controller_name' => 'DebtsController',
                    'session'=> $this->sessionDTO,
                    'title'=> "Upload Debts",

                ]);
            }


            $user = $entityManager->getRepository(User::class)->findOneBy(['id_user'=> $this->sessionDTO->getIdUser()]);

            $ui_generate = $this->getUniqueID();

            foreach ($arrayTransacao as $value) {

                $debts =  new Debts();

                $date = \DateTime::createFromFormat('Y-m-d', $this->convertDate($value[0]));
                $debts->setDate($date);

                $debts->setAmount($value[2]);

                $debts->setDescribe($value[1]);
                $debts->setUser($user);
                $debts->setService("Nubank");
                $debts->setTotal($sum);
                $debts->setUiGenerate($ui_generate);

                $date_card = explode("/", $value[3]);

                if(isset($date_card[0])) {
                    $portion = (int) $date_card[0];

                    $debts->setPortion($portion);
                }

                if(isset($date_card[1])) {
                    $number = (int) $date_card[1];
                    $debts->setNumberOfInstallments($number);
                }

                $debts->setCreatedAt(new \DateTime());

                $existing = $entityManager->getRepository(Debts::class)->findOneBy([
                    'amount' => $debts->getAmount(),
                    'date' => $debts->getDate(),
                    'describe' => $debts->getDescribe(),
                    'portion' => $debts->getPortion()
                ]);

                if ($existing === null) {

                    $entityManager->persist($debts);
                    $entityManager->flush();

                }


            }


        }

        return $this->redirectToRoute('app_debts_list');

    }

    private function getUniqueID()
    {
        $prefix = "GRP";
        $timestamp = time();
        return  ($prefix . '-' . $timestamp);
    }

    private function convertDate($dateString)
    {
            $date = DateTime::createFromFormat("d M", $dateString);
            if ($date instanceof DateTime) {
                return $date->format("Y-m-d");
            }

    }

   public  function validarData($data) {
        // Use uma expressão regular para verificar o formato
        if (preg_match('/^\d{2} (JAN|FEV|MAR|ABR|MAI|JUN|JUL|AGO|SET|OUT|NOV|DEZ)$/i', $data)) {
            return true; // A data está no formato válido
        } else {
            return false; // A data não está no formato válido
        }
    }

    public function getText($text)
    {
        $padrao = '/^(.*?) - (\d{1,2}\/\d{1,2})$/';

        if (preg_match($padrao, $text, $matches)) {
            return  $matches[2];

        } else {
            return null;
        }
    }
}

templates/debts/index.html.twig
{% extends 'base.html.twig' %}

{% set bank_param = bank is defined and bank is not empty ? bank : '' %}
{% set search_param = search is defined and search is not empty ? search : '' %}

{% set status_param = status is defined and status is not empty ? status : '' %}

{% set start_param = start is defined and start is not empty ? start : '' %}
{% set end_param = end is defined and end is not empty ? end : '' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white me-2">
                    <i class="mdi mdi-home"></i>
                </span> {{ title }}
                </h3>
            </div>
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">

                            <form class="form-sample" action="{{ path('app_debts_filter') }}" method="POST">
                                <input type="hidden" name="currency" value="BRL">
                                <p class="card-description"> Filter </p>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Search</label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="search"
                                                       value="{{ search_param }}"/>
                                            </div>
                                        </div>
                                    </div>

                                    <label class="col-sm-1 col-form-label">Service</label>
                                    <div class="col-sm-2">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" name="service" value="Nubank"
                                                        {% if bank_param == "Nubank" %}
                                                            checked
                                                        {% endif  %}
                                                > Nubank </label>
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="form-check">
                                            <label class="form-check-label">
                                                <input type="radio" class="form-check-input" name="bank" value=""
                                                        {% if bank_param == "" %}
                                                            checked
                                                        {% endif  %}
                                                > All </label>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Start</label>
                                            <div class="col-sm-9">
                                                <input type="date" class="form-control" name="start" value="{{ start_param }}"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">End</label>
                                            <div class="col-sm-9">
                                                <input type="date" class="form-control" name="end" value="{{ end_param }}" />
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-dribbble">Search</button>
                                    </div>
                                </div>
                                <br>

                            </form>

                            <h4 class="card-title">{{ title }}</h4>
                            <p class="card-description"> <code>
                                    <a href="{{ path('create_cash_flow') }}" class="badge badge-gradient-dark">+ADD</a>
                                </code>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Date</th>
                                    <th>Amount</th>
                                    <th>Description</th>
                                    <th>Service</th>
                                    <th>Portion</th>
                                    <th>N. of Ins</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% set total =0 %}
                                {% for debt in debts %}
                                    {% set total =  debt.total %}
                                    <tr class="{{ cycle(['odd', 'even'], loop.index0) }}">
                                        <td>{{ debt.idDebts }}</td>
                                        <td>{{ debt.date|date('d M Y H:i')  }}
                                        <td> {{ debt.amount }}</td>
                                        <td>{{ debt.describe|slice(0, 100) }}</td>
                                        <td>{{ debt.service }}</td>
                                        <td>{{ debt.portion }}</td>
                                        <td>{{ debt.numberOfInstallments }}</td>
                                        <td>
                                            <a href="{{ path('edit_cash_flow', {'id': debt.idDebts}) }}" class="badge badge-gradient-info">Edit</a>
                                            <a href="{{ path('delete_cash_flow', {'id': debt.idDebts}) }}" class="badge badge-gradient-danger">Delete</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <tfoot>
                            <tr>
                                <br>
                                <td colspan="4"></td>
                                <td><strong style="color: green;">Total R$ {{ total|number_format(2, ',', '.')  }}</strong></td><br><br>

                            </tr>
                            </tfoot>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/debts/upload-view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="main-panel">
        <div class="content-wrapper">

            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{ title }}</h4>
                        <form class="form-sample" action="{{ path('upload_debts_create') }}" method="POST" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>File upload</label>
                                        <input type="file" name="img[]" class="file-upload-default">
                                        <div class="input-group col-xs-12">
                                            <input type="file" class="form-control file-upload-info" name="upload" required>
                                            <span class="input-group-append">
                                                <button class="file-upload-browse btn btn-gradient-primary" type="submit">Upload</button>
                                              </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="col-sm-3 col-form-label">Bank</label>
                                        <div class="col-sm-9">
                                            <select class="form-control" name="bank">
                                                <option selected>Nubank</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}