src/Entity/Wallet.php
<?php

namespace App\Entity;

use App\Repository\WalletRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WalletRepository::class)]
class Wallet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_wallet = null;

    #[ORM\Column]
    private ?string $exchange = null;
    #[ORM\Column]
    private ?string $type_money = null;
    #[ORM\Column]
    private ?string $quantity;

    #[ORM\ManyToOne(targetEntity: Bitcoin::class)]
    #[ORM\JoinColumn(name: "id_bitcoin", referencedColumnName: "id_bitcoin"),]
    private ?Bitcoin $bitcoin;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2)]
    private $amount;

    #[ORM\Column(type: "decimal", precision: 10, scale: 2)]
    private $value_iten;

    #[ORM\Column(type: "datetime",nullable: true)]
    private $date;

    /**
     * @return mixed
     */
    public function getValueIten()
    {
        return $this->value_iten;
    }

    /**
     * @param mixed $value_iten
     */
    public function setValueIten($value_iten): void
    {
        $this->value_iten = $value_iten;
    }

    public function getIdWallet(): ?int
    {
        return $this->id_wallet;
    }

    /**
     * @return string|null
     */
    public function getExchange(): ?string
    {
        return $this->exchange;
    }

    /**
     * @param string|null $exchange
     */
    public function setExchange(?string $exchange): void
    {
        $this->exchange = $exchange;
    }

    /**
     * @return string|null
     */
    public function getTypeMoney(): ?string
    {
        return $this->type_money;
    }

    /**
     * @param string|null $type_money
     */
    public function setTypeMoney(?string $type_money): void
    {
        $this->type_money = $type_money;
    }

    /**
     * @return string|null
     */
    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    /**
     * @param string|null $quantity
     */
    public function setQuantity(?string $quantity): void
    {
        $this->quantity = $quantity;
    }



    /**
     * @return Bitcoin|null
     */
    public function getBitcoin(): ?Bitcoin
    {
        return $this->bitcoin;
    }

    /**
     * @param Bitcoin|null $bitcoin
     */
    public function setBitcoin(?Bitcoin $bitcoin): void
    {
        $this->bitcoin = $bitcoin;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date): void
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param mixed $amount
     */
    public function setAmount($amount): void
    {
        $this->amount = $amount;
    }

}

src/Controller/WalletController.php
<?php

namespace App\Controller;


use App\Repository\WalletRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class WalletController extends Controller
{
    #[Route('/wallet', name: 'app_wallet')]
    public function index(SessionInterface $session, WalletRepository $walletRepository): Response
    {
        if(($valid = $this->validSession($session)) === false) {
            return $this->render('index/index.html.twig',[ 'path' => $this->getPathEnv(),]);
        }

       $list = $walletRepository->findAll();

        $totalAmount = 0;
       if($list) {

           foreach ($list as $wallet) {
               $totalAmount += floatval($wallet->getAmount());
           }
       }

        return $this->render('wallet/index.html.twig', [
            'title'=> "List Wallet",
            'object'=> "List Wallet",
            'session'=> $this->sessionDTO,
            'path' => $this->getPathEnv(),
            'list' => $walletRepository->findAll(),
            'total'=> $totalAmount
        ]);
    }
}

templates/wallet/index.html.twig
{% extends 'base.html.twig' %}

{% block css %}

    <link rel="stylesheet" href="{{ asset(path ~'vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'vendors/css/vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
    <link rel="stylesheet" href="{{ asset(path ~'css/demo_1/style.css')}}">
    <link rel="shortcut icon" href="{{ asset(path ~'images/favicon.ico')}}" />

{% endblock %}

{% block title %} Bitcoin{% endblock %}

{% block body %}
<!-- partial -->
<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <form  action="" method="POST" >
                <button type="submit" class="btn btn-gradient-dark btn-fw">+ Adicionar</button>
            </form>
            <h3 class="page-title"> {{title}} </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">{{title}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ object }}</li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{title}}</h4>
                <div class="row">
                    <div class="col-12">
                        <table id="order-listing" class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Exchange</th>
                                <th>Currency</th>
                                <th>Type Money</th>
                                <th>Quantity</th>
                                <th>V. per item</th>
                                <th>Total</th>
                                <th>Date</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for item in list %}

                                <tr> <td>{{ item.idWallet }}</td>
                                    <td>{{ item.exchange }}</td>
                                   <td>
                                       {% if item.getBitcoin() is not null %}
                                        {{ item.getBitcoin().description }}
                                    {% else %}
                                        N/A
                                    {% endif %}
                                   </td>
                                    <td>{{ item.typeMoney }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.valueIten }}</td>
                                    <td>{{ item.amount }}</td>
                                    <td>{{ item.date | date('d-m-Y')  }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                        <tfoot>
                        <tr>
                            <br>
                            <td colspan="4"></td>
                            <td><strong style="color: blue;">Total: R$ {{ total}} </strong></td><br><br>
                        </tr>
                        </tfoot>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
        </div>
    </footer>

    <script src=".{{ asset(path ~'vendors/js/vendor.bundle.base.js')}}"></script>
    <script src="{{ asset(path ~'vendors/datatables.net/jquery.dataTables.js')}}"></script>
    <script src="{{ asset(path ~'vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
    <script src="{{ asset(path ~'js/off-canvas.js')}}"></script>
    <script src="{{ asset(path ~'js/hoverable-collapse.js')}}"></script>
    <script src="{{ asset(path ~'js/misc.js')}}"></script>
    <script src="{{ asset(path ~'js/settings.js')}}]"></script>
    <script src="{{ asset(path ~'js/todolist.js')}}"></script>
    <script src="{{ asset(path ~'js/jquery.cookie.js')}}"></script>
    <script src="{{ asset(path ~'js/data-table.js')}}"></script>

    {% endblock %}